[build]
  command = ""
  publish = "."
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"

# Serve index.html for all routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to Flask backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
