[build]
  command = "pip install -r requirements.txt"
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.11.8"

[functions]
  node_bundler = "esbuild"

[dev]
  command = "python app.py"
  port = 5000
