[build]
  command = "bash build.sh"
  publish = "build"

[build.environment]
  PYTHON_VERSION = "3.11"  # Using major.minor version for better compatibility
  NODE_VERSION = "18"

[dev]
  command = "python app.py"
  port = 5000
  publish = "."

[[redirects]]
  from = "/app/*"
  to = "/app"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
